export default {
  SELECT: 'Select',
  SELECT_DATE_RANGE: 'Select Date Range',
  NO_SELECT: 'NO-SELECT',
  FROM: 'From',
  TO: 'To',
  SEARCH: 'Search',
  YES: 'YES',
  NO: 'NO',
  DESCRIPTION_PLACEHOLDER: 'Type description here',
  PROJECTS: 'Projects',
  WORK_HOURS: 'Total Worked Hours',
  LEAVES: 'Leaves',
  NOT_ALLOWED: 'Not Allowed',
  EMPLOYEE_LIST_ERROR: 'Problem in fetching employee list',
  DUBLICATE_ENTRY_ERROR: 'You have previous same timesheet entry',
  EMPTY_TIMESHEET: 'Empty Timesheet',
  EMPTY_TIMESHEET_MSG: 'Add timesheet before saving',
  NO_TIMESHEET_PRESENT: 'No timesheet present for current filter',
  NO_TIMESHEET_ADDED: 'No Timesheet Added',
  WORK_HOURS_ERROR: 'Work hours is a required field',
  EDIT_SUCCESS: 'Timesheet Updated!',
  EDIT_ERROR: 'Problem in updating timesheet, please try again!',
  DELETE_SUCCESS: 'Timesheet Deleted!',
  DELETE_ERROR: 'Delete Request Failed!',
  UPDATE_SKILLS_SUCCESS: 'Skills updated successfully',
  UPDATE_SKILLS_ERROR: 'Something Went Wrong!',
  CREATE_ERROR: 'Problem in creating timesheet!',
};
