export default {
  SELECT: 'Select',
  SELECT_DATE_RANGE: 'Select Date Range',
  NO_SELECT: 'NO-SELECT',
  FROM: 'From',
  TO: 'To',
  SEARCH: 'Search',
  YES: 'YES',
  NO: 'NO',
  DESCRIPTION_PLACEHOLDER: 'Type Description here',
  PROJECTS: 'Projects',
  WORK_HOURS: 'Total Worked Hours',
  LEAVES: 'Leaves',
  NOT_ALLOWED: 'Not Allowed',
  DUBLICATE_ENTRY_ERROR: 'You have previous same timesheet entry',
  EMPTY_TIMESHEET: 'Empty Timesheet',
  EMPTY_TIMESHEET_MSG: 'Add timesheet before saving',
  NO_TIMESHEET_PRESENT: 'No Timesheet Present for current filter',
  NO_TIMESHEET_ADDED: 'No timesheet Added',
  WORK_HOURS_ERROR: 'Work Hours is a required field',
};
